# Generated by Django 3.1.2 on 2020-10-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sum', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sum', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bank', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addexpenses')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addincome')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addincome')),
            ],
        ),
        migrations.CreateModel(
            name='CheckExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addexpenses')),
            ],
        ),
        migrations.AddField(
            model_name='addincome',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bankaccount'),
        ),
        migrations.AddField(
            model_name='addincome',
            name='category_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoryincome'),
        ),
        migrations.AddField(
            model_name='addincome',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor'),
        ),
        migrations.AddField(
            model_name='addincome',
            name='specific_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specificproject'),
        ),
        migrations.AddField(
            model_name='addincome',
            name='tag',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='addexpenses',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bankaccount'),
        ),
        migrations.AddField(
            model_name='addexpenses',
            name='category_expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoryexpenses'),
        ),
        migrations.AddField(
            model_name='addexpenses',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor'),
        ),
        migrations.AddField(
            model_name='addexpenses',
            name='specific_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specificproject'),
        ),
        migrations.AddField(
            model_name='addexpenses',
            name='tag',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
    ]
