# Generated by Django 3.1.2 on 2020-10-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201021_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpenses',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='addincome',
            name='tag',
        ),
    ]
