# Generated by Django 3.1.2 on 2020-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='date',
            field=models.DateField(),
        ),
    ]
