# Generated by Django 3.1.2 on 2020-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201024_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpenses',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
