# Generated by Django 3.1.2 on 2020-11-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bankaccount_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='deleted',
        ),
    ]
