# Generated by Django 3.1.2 on 2020-11-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_bankaccount_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpenses',
            name='category_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoryexpenses'),
        ),
        migrations.AlterField(
            model_name='addexpenses',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contractor'),
        ),
        migrations.AlterField(
            model_name='addexpenses',
            name='specific_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specificproject'),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount'),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='category_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoryincome'),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contractor'),
        ),
        migrations.AlterField(
            model_name='addincome',
            name='specific_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specificproject'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses'), ('BankTransaction', 'BankTransaction')], max_length=15)),
                ('sum', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount')),
                ('category_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoryexpenses')),
                ('category_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoryincome')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contractor')),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_from', to='api.bankaccount')),
                ('send_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_to', to='api.bankaccount')),
                ('specific_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specificproject')),
            ],
        ),
    ]
