# Generated by Django 3.1.2 on 2020-11-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201114_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
