# Generated by Django 3.1.2 on 2020-11-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201120_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addincome',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='addincome',
            name='category_income',
        ),
        migrations.RemoveField(
            model_name='addincome',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='addincome',
            name='specific_project',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='account_from',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='account_to',
        ),
        migrations.DeleteModel(
            name='AddExpenses',
        ),
        migrations.DeleteModel(
            name='AddIncome',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
    ]
