# Generated by Django 3.1.2 on 2020-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201121_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
