# Generated by Django 3.1.2 on 2020-11-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_contractor_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='deleted',
        ),
    ]
