# Generated by Django 3.1.2 on 2020-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_contractor_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
