# Generated by Django 3.1.2 on 2020-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bankaccount_deleted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificproject',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
